export const UPDATE_APPOINMENTS = 'UPDATE_CONTACTS';
export const ADD_APPOINMENT = 'ADD_APPOINMENT';
export const DELETE_APPOINMENT = 'DELETE_APPOINMENT';
export const UPDATE_APPOINMENT = 'UPDATE_APPOINMENT';

