export const UPDATE_PATIENTS = 'UPDATE_PATIENTS'
export const ADD_PATIENT = 'ADD_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const ADD_PRES_TO_PATIENT = 'ADD_PRES_TO_PATIENT'
export const DEL_PRES_TO_PATIENT = 'DEL_PRES_TO_PATIENT'
export const UPT_PRES_TO_PATIENT = 'UPT_PRES_TO_PATIENT'


